### ISSUE TITLE
Export survey timestamps

### ISSUE THREAD

**Issue by dadrivr** [OuhscBbmc/REDCapR#184] opened 2018-01-31 07:04 UTC
I'm not sure if this is already a feature and I'm just missing how to implement it, but I'm not seeing an option to export the survey timestamps--e.g., see the "survey" argument of the `exportRecords()` function from the redcapAPI package.  Love the package guys!

**Comment by wibeasley** [comment] 2018-01-31 13:26
Thanks for the input, @dadrivr.  I'll close this issue, because it's a duplicate of #159.  It certainly sounds like there are enough people to make this  worth implementing.  I'll try to do it in the next week or two.

**Closed by wibeasley** 2018-01-31 13:26 UTC
