### ISSUE TITLE
parsing failures warnings using redcap_read_oneshot function

### ISSUE THREAD

**Issue by zhangrz2019** [OuhscBbmc/REDCapR#282] opened 2019-12-26 17:47 UTC
By comparing the old and new source code for function redcap_read_oneshot, a new package "checkmate" were used. I do not believe by default, the install.packages("REDCapR") installs "checkmate" packages. Also, it seems redcap_read_oneshot function generates parsing failure warning messages. A part of my data was not parsed and that very same field that is incomplete parsing is numeric when I set the field to be character in redcap. Can you investigate?

**Comment by wibeasley** [comment] 2019-12-26 19:37
Hi @zhangrz2019, will you install the version from GitHub, and see if these two problems are addressed?

The first one was fixed in #32 

If the second problem isn't, will you please paste some non-PHI data that isn't parsed correctly?

**Comment by zhangrz2019** [comment] 2019-12-27 15:33
It seems the problem is still not resolved after I installed the developer REDCapR package from github. Here is the none PHI data query results warning message:

Warning: 346 parsing failures.
 row      col expected   actual         file
2320 study_id a double NCL08185 literal data
2321 study_id a double NCL08185 literal data
2322 study_id a double NCL08185 literal data
2323 study_id a double NCL08185 literal data
2324 study_id a double NCL08185 literal data
.... ........ ........ ........ ............
See problems(...) for more details.

few lines where the problems occured:


  row.names| sample_id | redcap_event_name | p_sample_type | study_id | p_sample_consumed

2309 | 1496GD02A | 1_arm_1 | 5b | 1496 | NA
2310 | 1496GD02B | 1_arm_1 | 5b | 1496 | NA
2311 | 1496GD02C | 1_arm_1 | 5b | 1496 | NA
2312 | 1496GD02D | 1_arm_1 | 5b | 1496 | NA
2313 | 1496GD02E | 1_arm_1 | 5b | 1496 | NA
2314 | 1496GD02F | 1_arm_1 | 5b | 1496 | NA
2315 | 3016SS01A | 1_arm_1 | 5b | 3016 | 0
2316 | 3101ZS02A | 1_arm_1 | 5b | 3101 | NA
2317 | 3101ZS02B | 1_arm_1 | 5b | 3101 | NA
2318 | 3101ZS02C | 1_arm_1 | 5b | 3101 | NA
2319 | 3101ZS02D | 1_arm_1 | 5b | 3101 | NA
2320 | 08185MO03A | 1_arm_1 | 5b | NA | NA
2321 | 08185MO03B | 1_arm_1 | 5b | NA | NA
2322 | 08185MO03C | 1_arm_1 | 5b | NA | NA
2323 | 08185MO03D | 1_arm_1 | 5b | NA | NA
2324 | 08185MO03E | 1_arm_1 | 5b | NA | NA

note that row 2320 is where the problem began. The study_id should be a character variable but the output results suggested it is numeric.

**Comment by zhangrz2019** [comment] 2019-12-27 15:48
I did further testing. I added a record whose sample_id is 0000TT01A and its study ID set to A000. When I re-run the query using the same code. This time, the query did not generate parsing failure warnings. I wonder if somewhere in the redcap_read_oneshot() function is looking at first portion of data and self determine the variable type instead of looking at variable settings in REDCap database.

**Comment by wibeasley** [comment] 2019-12-27 18:08
Yea, good job investigating further.  You're right about the cause.  Read the [`redcap_read_oneshot()`](https://ouhscbbmc.github.io/REDCapR/reference/redcap_read_oneshot.html) documentation for two other approaches:
1. increase the value of `guess_max`, or
1. specify the desired `col_types`

A third way is to use [`redcap_read()`](https://ouhscbbmc.github.io/REDCapR/reference/redcap_read.html).

I'm closing the issue b/c I'm pretty sure this is the common case that happens to thesee types of apparently-numeric values when they're sorted in a big dataset.  Please reopen if I'm wrong.

**Closed by wibeasley** 2019-12-27 18:08 UTC
