### ISSUE TITLE
redcap_read() Error with Repeatable Forms

### ISSUE THREAD

**Issue by amaclay** [OuhscBbmc/REDCapR#143] opened 2017-03-21 14:57 UTC
Random REDCap user here who noticed a potential bug.

REDCap exports two additional columns when querying a project with repeatable forms: "redcap_repeat_instrument" and "redcap_repeat_instance". The trouble arises if all records in a batch (default batch size is 100L) have no instances of any repeated forms; REDCap omits these columns in that batch and the call fails on data.table::rbindlist(lst_batch): inconsistent number of columns.

I don't know whether this is better reported here as a REDCapR issue or as a REDCap bug. I doubled the batch size as a workaround but thought it was worth mentioning.

**Comment by wibeasley** [comment] 2017-03-21 19:31
Thanks for the heads up, @amaclay.  I haven't spent time on the repeatable forms.  I've been putting it off b/c we're re-writing the record export function (see #138 & [eav-playground.R](https://github.com/OuhscBbmc/REDCapR/blob/master/playgrounds/eav-playground.R)).

I'm hoping another layer of `tidyr::crossing()` (informed by the metadata before running through `tidyr::spread()`) should prevent different batches from having different columns.

If you have a de-identified dataset & dictionary, I'll incorporate it into our test suite so we'll cover your scenario.

(cc: @nutterb, any thoughts if [redcapAPI](https://github.com/nutterb/redcapAPI) is set up better to deal with repeatable forms?  --it's that new feature announced around the last REDCapCon.)

**Comment by nutterb** [comment] 2017-03-21 20:38
`redcapAPI` will choke on this as well.  It still uses `rbind`. If I ever get back to it, I want to using `dplyr::bind_rows` instead, which will handle it gracefully.  But for now, increasing the batch size is the only option.

(Caveat: `redcapAPI` doesn't batch by default, so it may succeed if used with the defaults.  But I'm not sure how it will react to the repeating forms, having never tried it)

**Comment by dadrivr** [comment] 2018-02-27 14:01
I'll put a vote in for this, as well.  We're using repeating instruments (for coding) and will need to be able to export those data to check inter-rater reliability.  Many thanks!

**Comment by wibeasley** [comment] 2018-02-27 15:35
yikes, has this been almost a year.  I'm sorry.  Thanks @dadrivr, it's definitely on our list.  Right now we're handling it after REDCapR, but would like to move all that logic into the REDCapR layer.  It means that multiple `data.frame`s would be returned --one for each repeating form.  This should be more feasible to accommodate when I start using EAV underneath.

**Comment by jasonpott** [comment] 2019-01-15 08:37
I came across this issue with a dataset with several repeating forms. Is there any advice on how to manage this issue when importing the dataset?

**Comment by wibeasley** [comment] 2019-01-15 18:11
@jasonpott, I don't have any tidy advice for repeating forms.  It's something that we're using some in our projects, and eventually would like it better encapsulated in REDCapR itself.  For now, our projects do the manipulation before it gets to REDCapR.

Rephrasing what I said above, we treat that larger REDCap dataset as a [block matrix](http://mathworld.wolfram.com/BlockMatrix.html), and try to isolate & address each individual block separately, instead of all at once

Here's a simple example from one of our recent projects.  In this case, 'medication' is a repeating form within a REDCap project where each parent/main row represents a single patient. It's a simple example because it's bulk updating fresh data, and doesn't need to worry about overwriting a patient's `redcap_repeat_instance` value.  I was hoping to gain a little more real  experience (with complex examples) before including them into REDCapR.  

Any ideas/concerns would be appreciated.

```r
ds_medication <-
  ds_medication %>%
  dplyr::mutate(
    medication_instructions       = dplyr::coalesce(medication_instructions , "--")
  ) %>%
  dplyr::group_by(patient_id_smushed) %>%
  dplyr::mutate(
    # Add REDCap-specific fields
    redcap_repeat_instrument	     = "medication",
    redcap_repeat_instance           = seq_len(n())
  ) %>%
  dplyr::ungroup() %>%
  dplyr::select(
    redcap_repeat_instrument,
    redcap_repeat_instance,
    dplyr::everything()
  )

...

REDCapR::redcap_write(
  ds_to_write = ds_patient,
  redcap_uri  = credential_patient$redcap_uri,
  token       = credential_patient$token,
  batch_size  = 1000L
)
REDCapR::redcap_write(
  ds_to_write = ds_medication,
  redcap_uri  = credential_patient$redcap_uri,
  token       = credential_patient$token,
  batch_size  = 1000L
)
```

**Comment by wibeasley** [comment] 2019-01-15 18:57
> We increased the batch_size so that it always includes at least one record with a repeated survey.

You're talking about the `batch_size` argument in [`redcap_read()`](https://ouhscbbmc.github.io/REDCapR/reference/redcap_read.html)?  Is that so the data type of each column is set to something other than `logical`?  I like the advice.

If that isn't feasible in a future project, you could also set `guess_type` to FALSE, and convert the types explicitly.

**Comment by jasonpott** [comment] 2019-01-22 15:39
@wibeasley Thank you for your reply, sorry for the radio silence. 

I'll take a look at implementing your advice in my usecase. I want to analyse the data at a form level so this approach would not be a compromise.

**Comment by wibeasley** [comment] 2021-11-05 05:14
@amaclay , @jasonpott, & @isaactpetersen, I believe was fixed with the [Oct 2019 changes](https://github.com/OuhscBbmc/REDCapR/commits/main/R/redcap-read.R), that held tighter control of the columns.

I created a new test project that replicates your scenario.  Notice how patients 3, 4, & 5 don't have the 'bp' repeated instrument.  Only patients 1 & 2 have 'bp'.  So when a batch doesn't include 1 or 2, it should reproduce the problems you saw with the old version, correct?  As of tonight, the test suite tries batches of sizes, 3, 2, & 1.  All three of these should reproduce the old problem --and all three pass.

I'm closing the issue, but tell me if the latest GitHub version of REDCapR still exhibits the problem.

Btw, our group's code still makes separate REDCapR calls --one for each repeating instrument.  It's just more natural for us to deal with and analyze.  But I wanted this to be error-free.

![image](https://user-images.githubusercontent.com/1372890/140460593-59d0f153-f9ed-442e-906b-76e13168180b.png)


```r
>       redcap_read(
+         redcap_uri    = credential$redcap_uri,
+         token         = credential$token,
+         batch_size    = 1
+       )
The data dictionary describing 11 fields was read from REDCap in 0.3 seconds.  The http status code was 200.
5 records and 3 columns were read from REDCap in 0.2 seconds.  The http status code was 200.                                                    
Starting to read 5 records  at 2021-11-04 23:11:14.
Reading batch 1 of 5, with subjects 1 through 1 (ie, 1 unique subject records).
4 records and 15 columns were read from REDCap in 0.2 seconds.  The http status code was 200.                                                   
Reading batch 2 of 5, with subjects 2 through 2 (ie, 1 unique subject records).
2 records and 15 columns were read from REDCap in 0.2 seconds.  The http status code was 200.                                                   
Reading batch 3 of 5, with subjects 3 through 3 (ie, 1 unique subject records).
1 records and 15 columns were read from REDCap in 0.2 seconds.  The http status code was 200.                                                   
Reading batch 4 of 5, with subjects 4 through 4 (ie, 1 unique subject records).
1 records and 15 columns were read from REDCap in 0.2 seconds.  The http status code was 200.                                                   
Reading batch 5 of 5, with subjects 5 through 5 (ie, 1 unique subject records).
1 records and 15 columns were read from REDCap in 0.2 seconds.  The http status code was 200.                                                   

── Column specification ─────────────────────────────────────────────────────────────────────────────────────
cols(
  record_id = col_double(),
  redcap_repeat_instrument = col_character(),
  redcap_repeat_instance = col_double(),
  date_enrolled = col_date(format = ""),
  first_name = col_character(),
  dob = col_date(format = ""),
  age = col_double(),
  ethnicity = col_double(),
  race = col_double(),
  sex = col_double(),
  demographics_complete = col_double(),
  date_bp = col_date(format = ""),
  bp_systolic = col_double(),
  bp_diastolic = col_double(),
  bp_complete = col_double()
)

$data
  record_id redcap_repeat_instrument redcap_repeat_instance date_enrolled first_name        dob age
1         1                     <NA>                     NA    2019-10-14        aaa 2010-10-14 8.9
2         1                       bp                      1          <NA>       <NA>       <NA>  NA
3         1                       bp                      2          <NA>       <NA>       <NA>  NA
4         1                       bp                      3          <NA>       <NA>       <NA>  NA
5         2                     <NA>                     NA    2019-02-02        bbb 2010-02-02 9.6
6         2                       bp                      1          <NA>       <NA>       <NA>  NA
7         3                     <NA>                     NA    2021-11-04    empty 3       <NA>  NA
8         4                     <NA>                     NA    2021-11-04    empty 4       <NA>  NA
9         5                     <NA>                     NA          <NA>    empty 5       <NA>  NA
  ethnicity race sex demographics_complete    date_bp bp_systolic bp_diastolic bp_complete
1         1    4   0                     2       <NA>          NA           NA          NA
2        NA   NA  NA                    NA 2019-10-14         110          100           2
3        NA   NA  NA                    NA 2019-10-14         111          101           2
4        NA   NA  NA                    NA 2019-10-14         112          102           2
5         0    6   1                     2       <NA>          NA           NA          NA
6        NA   NA  NA                    NA 2004-04-04         114          104           2
7        NA   NA  NA                     0       <NA>          NA           NA          NA
8        NA   NA  NA                     0       <NA>          NA           NA          NA
9        NA   NA  NA                     0       <NA>          NA           NA          NA

$success
[1] TRUE

$status_codes
[1] "200; 200; 200; 200; 200"

$outcome_messages
[1] "4 records and 15 columns were read from REDCap in 0.2 seconds.  The http status code was 200.; 2 records and 15 columns were read from REDCap in 0.2 seconds.  The http status code was 200.; 1 records and 15 columns were read from REDCap in 0.2 seconds.  The http status code was 200.; 1 records and 15 columns were read from REDCap in 0.2 seconds.  The http status code was 200.; 1 records and 15 columns were read from REDCap in 0.2 seconds.  The http status code was 200."

$records_collapsed
[1] ""

$fields_collapsed
[1] ""

$forms_collapsed
[1] ""

$events_collapsed
[1] ""

$filter_logic
[1] ""

$datetime_range_begin
[1] NA

$datetime_range_end
[1] NA

$elapsed_seconds
[1] 4.310187
```

**Closed** 2021-11-05 05:14 UTC
